import { Link } from 'react-router-dom'
import type { IndexBundle } from '@defi-dna/data'
import { feeds } from '../lib/registry.ts'
import { useChangelog } from '../hooks/useIndex.ts'
import { dateInfo } from '../lib/view.ts'
import { IconArrow } from '../components/Icons.tsx'
import { Info, SourceMark } from '../components/UI.tsx'

const MAX_SHOWN = 300

/** Append-only log of what moved between runs. We add nothing to it. */
export const ChangelogPage = ({ index }: { index: IndexBundle }) => {
  const { data } = useChangelog()
  const events = data ?? []
  const feedName = (id: string) => feeds.find((feed) => feed.id === id)?.name ?? id

  return (
    <>
      <section className="page-intro">
        <span className="eyebrow">THE RUN LOG</span>
        <h1>
          What changed.
          <br />
          <span>And when it changed.</span>
        </h1>
        <p>
          Every refresh is compared with the one before it and the differences are appended here.
          These are movements in what the feeds published — the interpretation is yours.
        </p>
      </section>

      <div className="section-heading">
        <div>
          <h2>
            Recent events <span className="count-badge">{events.length}</span>
          </h2>
          <p>Newest first, capped at the last {MAX_SHOWN} entries.</p>
        </div>
        <span className="section-aside">
          Data cut {dateInfo(index.generatedAt).label}
          <Info label="Where this comes from">
            The log is generated by diffing consecutive pipeline runs and is committed to the
            repository with the data, so the git history and this page agree.
          </Info>
        </span>
      </div>

      {events.length === 0 ? (
        <div className="empty-state">
          <h3>Nothing recorded yet</h3>
          <p>The log fills up from the second pipeline run onward.</p>
          <Link className="button primary" to="/">
            Back to the matrix <IconArrow />
          </Link>
        </div>
      ) : (
        <div className="change-list">
          {events.slice(0, MAX_SHOWN).map((event, index) => (
            <div
              className="change-row"
              key={`${event.ts}-${event.protocolId}-${event.feedId}-${index}`}
            >
              <span className="change-when">{event.ts.slice(0, 10)}</span>
              <span className="change-subject">
                <SourceMark id={event.feedId} />
                <span>
                  {feedName(event.feedId)}
                  <small>{event.from === null ? 'first value' : 'value changed'}</small>
                </span>
              </span>
              <span className="change-body">
                <Link to={`/protocol/${event.protocolId}`} className="text-link">
                  {event.protocolName}
                </Link>
                <span className="change-from">{event.from ?? '—'}</span>
                <span className="change-arrow">→</span>
                <span className="change-to">{event.to ?? '—'}</span>
              </span>
            </div>
          ))}
        </div>
      )}

      <div className="page-end-note">
        <span>Looking for the full history of a single cell?</span>
        <a
          className="text-link"
          href="https://github.com/cp0x-org/defi-dna-data/commits/main"
          target="_blank"
          rel="noreferrer noopener"
        >
          Browse the git log <IconArrow />
        </a>
      </div>
    </>
  )
}
